_config.yml

same cleaning as for example lesson

clean _config.yml

---

README.md
brainstorming.md

this is just a start. Thought it made sense to have a dirty lesson planning document instead of polluting the lessons, before the structure of the lessons has  even been decided

add document for brainstorming and planning

---

_episodes/00-preparation.md
_episodes/01-intro.md
_episodes/03-operations.md
_episodes/04-lessons.md
_episodes/05-partnership.md
_episodes/06-teaching.md
_episodes/07-future.md

to match CodeRefinery instructor workshop agenda

added episodes (to be filled)

---

_episodes/00-preparation.md

- less capitalization
- adjusted heading levels for easier reading (for me)

cosmetic adjustments in the preparation episode

---

_episodes/02-teachingstyle.md

- Currently in 02-teachingstyle but could be more later.

Minor revisions

---

_episodes/09-future.md

- Working base so that others can contribute to different sections.

09-future: Provide outline

---

_episodes/01-intro.md
_episodes/02-teachingstyle.md
_episodes/03-lightningoverview.md
_episodes/07-partnership.md

update timing to match new schedule proposed in https://github.com/coderefinery/coderefinery.org/pull/304
also new discussion exercise about sustainability

small updates

---

_episodes/06-lessons.md

- This has the necessary introduction and the links to the manuals.  I
think that this is minimally sufficient, but needs revisions.
- I don't know the technical process of creating a new lesson.
- This is a base for other minor or major revisions.

06-lessons: Add a basic outline of topics

---

_episodes/09-future.md

- Enough to start and have a discussion

Basic outline of Hand-on SciComp

---

_episodes/09-future.md

- First draft of Nordic plan
- Later, I will add a figure
- Others should also comment on if you agree, it's OK to disagree.
- Needs more revisions but can be merged as a working draft.

06-future: minimal Nordic collaboration/organization section

---

_episodes/07-partnership.md

- I couldn't find many easy improvements here, it looked pretty good.
- I made the following sections:
- Challenges: explicitly discuss
- Give the example of existing recurring workshops at Aalto and
possibly KTH.
- Add concrete options of how in-kind contributions could work

07-partnerships: add challenges, concrete plans, recurring workshop example

---

_episodes/06-lessons.md

- Iterate to attempt to clarify and improve

06-lessons.md: General small revisions

---

_episodes/01-intro.md

One change to carefully review is "Goal of this workshop". I want to avoid that these are only my goals. I hope I have not missed important goals.

Work on "intro"

---

_episodes/01-intro.md

 Sabry adding his philosophies

---

_episodes/01-intro.md

rkdarst teaching philosophy

---

_episodes/03-lightningoverview.md

- I added some important bullet points, but it's too much to do for
every lesson.  Instead, the presenters will hopefully pick and
choose the most important ones for each lesson.

Add suggestions for what to cover in the lightning overviews

---

_episodes/06-lesson-design.md

Now moving on to other episodes ...

minor tweaks in "lesson design" episode

---

_episodes/00-preparation.md

Maybe not super relevant anymore for this workshop but then I have to prepare less for the next one.

Shorten and update the preparation text

---

_episodes/06-teaching.md

Based on discussion this noon I threw away almost all of the previous exercise content and replaced it by group work that will practice teaching a short segment/topic.
Watching the live demo videos is left as optional reference.

group exercise practicing teaching

---

_episodes/07-future.md

I have removed a lot of text and tried to make this fit into 20 minutes.

work on the "future" episode

---

_episodes/07-future.md

- This is my first draft with included images
- I don't think it needs to be much longer
- To review: please check text carefully, it probably needs some
revisions still.  I also haven't verified that images work.

07-future: mention skills map and scicomp community

---

content/conf.py
requirements.txt

- Add the sphinx_rtd_theme color contrast extension
- sphinx-lesson is now released
- Review: does CI pass?

Add sphinx_rtd_theme color contrast extension, sphinx-lesson released

---

content/index.rst
content/lesson-design.md
content/lesson-development.md

they will be presented at different times by possibly
different instructors - this is to make it possible
to develop these episodes in parallel
the first is more conceptual, the second more organizational/technical

split lesson design and development into two episodes

---

content/lesson-design.md

- less text
- less duplication w.r.t. manual
- update recommended reading
- placeholder for an example (we need to add that later)
- add some HPC examples

work on the "lesson design" episode and exercise

---

content/conf.py
requirements.txt

Add sphinx coderefinery branding

---

content/01-intro.md
content/04-running-workshops.md
content/index.rst
content/lesson-development.md

- Fix small sphinx errors (except in 03-teaching-style which has an
open PR).
- Review: does CI pass?

Fix sphinx errors

---

content/lesson-design.md

- convert to lighter markup (away from "carpentries" markup)
- add example for backwards design; closes #134

more work on the lesson design episode

---

content/03-teaching-style.md

Customization for the HPC trainer training event

Teaching style nov 2020 hpc

---

content/02-teaching-philosophies.md
content/03-teaching-style.md

- fix heading level
- de-indent some blocks (I didn't know a block like that could become
a code block inside a list)
- Review: does CI pass without warnings)

myst syntax fixes

---

content/03-teaching-style.md

Sabry syntax fixes

---

content/06-teaching.md
content/index.rst

For review I recommend to only look at the first commit. The second commit only contains markup changes.

Small adjustments in teaching exercise

---

content/index.rst

- Add brief description of the course
- Add prerequisites
- Learners tomorrow won't be directly directed here, but we should
show something so it doesn't look empty.
- Review: especially look at the content of these and make sure that
it's not objectionable to anyone.  It won't be perfect, but can be
iterated later.

content/index: Update the front matter on index page

---

content/index.rst

- Based on ideas in #120 (but doesn't close it)
- Try to list some general learner personas that I hope we can agree
on.  But this doesn't intend to be the last word on the matter.
- Review: is this generally non-objectionable - enough for tomorrow
and a starting point for future iteration?

content/index: Add learner personas

---

content/index.rst

- Give a summary of the course (is this even useful?  There is a table
of contents right above... I think later this could be expanded with
more about what is covered, to further help people decide if the
coures is for them, after reading everything above).
- A "See Also" seciton that lists some of our most common resources.
- Review: semi-detailed read, ensure nothing is missing and nothing is
completely wrong.  It can be further improved later.

content/index: Improve bottom matter

---

content/about-coderefinery.md
content/index.rst
content/welcome.md

- as discussed in our meeting hackmd
- the content of the "welcome" part will be updated in an upcoming pull
request

split intro into "welcome" and "about CR"

---

content/lesson-design.md

Tried to take HPC carpentry lesson as an example for backwards lesson design. The idea is to make it easier for learners to link it to what they will be doing after the training (write own tutorial for application domain workshops).

Try to add some more info about lesson design

---

content/index.rst

- Minor update to teach CR lesson persona
- Emphasize the useful spot for the tech specialist teacher
- Add new persona for the collaboration network.
- Review: actual content

content/index: learner personas, update + new (collab network)

---

content/03-teaching-style.md

"Discussion/group work: Top issues new instructors face " #137

Sabry issues facedby instructors

---

content/teaching-strategies.md

- Begin filling out text
- This can be merged, but I will keep iterating on it as well.
- Initial review requests for now:
- is the general plan good?
- Suggestions for the future?
- Does HackMD, breakout rooms, etc go here?  I am assuming not,
since more people need to know teaching strategies than those
other things, so we should devote more time for the pure teaching
mechanics.

content/teaching-strategies: Update lesson

---

content/lesson-design.md

Review: only last 3 commits. First 3 commits are only reformatting the text for more silent diffs.

Cosmetics in "lesson design"

---

content/teaching-strategies.md

- Various minor revisions
- Review: minimal needed, review whole lesson after merging.

content/teaching-strategies: various updates

---

content/04-running-workshops.md
content/teaching-strategies.md

- Move "online teaching discussion" to running a workshop
- Add "see also" section
- Various other minor fixups
- Review: minimal

content/teaching-strategies:

---

content/teaching-strategies.md

- Review: general check, also does this belong here or in "running
workshops".  I think it's OK to mention it beiefly here, since it
relates to the actual teaching part, too.

content/teaching-strategies: Add a section on dealing with questions

---

content/conf.py

content/conf: Fix github link

---

content/02-teaching-philosophies.md

- Ask how informal vs structured teaching is.
- Review: make sure it make sense.

content/02-teaching-philosophies: add another introductory question

---

content/lesson-development.md

- Also ask what difficulties there are in collaborative lesson
development.
- Review: minimal?

content/lesson-development: intro question, mention difficulties

---

content/lesson-development.md

I made it a bit less CR-specific, addressed some comments from #169.

group/reorganize episode; closes #163

---

content/teaching-strategies.md

- Review: does CI pass without warnings?

content/teaching-strategies: remove empty questions block that caused warning

---

content/03-teaching-style.md

- workshops-online doesn't exist yet, but will after merging another
PR.
- Review: does CI pass without warnings

Fix links from `make linkcheck`

---

.github/workflows/spellcheck.yml
content/02-teaching-philosophies.md
content/03-teaching-style.md
content/lesson-design.md

Noticed a few typos and thought perhaps your spellchecking wasn't working.

Fix spellchecking
